"""AR-008 curated playbooks (DEC-001: curated, not generative). Fictional, generic: no real brands, numbers or links.
Provider/regulator/police procedures are UNVERIFIED for Zimbabwe: any step that depends on them carries local=True (TO BE VERIFIED)."""
SAFE = (0, "Nothing lost yet — you have not acted.")
STOP = (1, "Fully recoverable if you stop here.")
NOTICE = "Typical progression for this kind of attack — a simulation, not a prediction of one specific criminal. Nothing is sent, opened or paid."
LOCAL = "Local provider, bank and police procedures are TO BE VERIFIED before being relied on."

PB = {
 "Financial Scam": dict(title="Payment / mobile-money scam",
   hook="The lure creates pressure so you act before thinking.",
   act="You are at the decision point. The message wants {ask}. A genuine provider would not ask for it by message.",
   ext="You hand over {ask}. The attacker can now approve payments as you.",
   out="Funds are moved out of your wallet within minutes and split across cash-out agents and other wallets.",
   r2=(2, "Partly recoverable — a provider may be able to flag or hold the transaction if you call at once on an independently sourced number.", True),
   r3=(3, "Hard to undo — cashed-out money is rarely recovered. Speed decides the outcome.", True),
   click="You tap the link. A look-alike 'confirmation' screen asks for your PIN (illustration only — nothing real is opened).",
   nxt="Scammer (typical): \"Quick — the reversal fails if you delay. Send it now or the money is lost.\"", press="If you hesitate: \"Your wallet will be blocked in 10 minutes.\""),
 "Phishing": dict(title="Fake sign-in / account-warning phishing",
   hook="A warning about your account makes you feel you must act now.",
   act="You are at the decision point. The message wants {ask} through a link or reply.",
   ext="Your login details are captured on a fake sign-in page that looks familiar.",
   out="Account takeover: the password is changed, your contacts are messaged, and data or money is taken.",
   r2=(2, "Partly recoverable — change your password from the official service and sign out other sessions before they are used.", False),
   r3=(3, "Hard to undo — the takeover may already have happened; recovery means regaining the account and checking the damage.", True),
   click="You tap the link. A fake sign-in page copies a familiar service and asks for your login (illustration only).",
   nxt="Scammer (typical): \"Your account is still at risk — confirm your details now to avoid closure.\"", press="If you hesitate: \"Final warning: access ends in 1 hour.\""),
 "Identity Fraud": dict(title="Identity / KYC-style fraud",
   hook="A 'verification' request makes handing over identity details feel routine.",
   act="You are at the decision point. The message wants {ask}. Legitimate services do not collect these by message.",
   ext="You hand over {ask}. The attacker can now pass identity checks as you.",
   out="Accounts, SIMs or wallets are opened or taken over in your name.",
   r2=(2, "Partly recoverable — a PIN, OTP or password can be changed; an ID number cannot be re-issued, so watch for misuse.", False),
   r3=(3, "Hard to undo — identity misuse can surface later. Report it and monitor your accounts.", True),
   click="You follow the request. A 'verification form' asks for ID number, password and a code (illustration only).",
   nxt="Scammer (typical): \"We only need one more code to finish your verification.\"", press="If you hesitate: \"Your SIM/account will be blocked today.\""),
 "Malicious Link": dict(title="Malicious link or attachment",
   hook="A curiosity or payment lure makes you want to open something.",
   act="You are at the decision point. The message wants {ask}. Opening it is the attack.",
   ext="Credentials are captured by a fake page, or a malicious file runs on your device.",
   out="Your device or accounts are compromised and used to steal data or attack others.",
   r2=(2, "Partly recoverable — disconnect, change credentials from a clean device and scan for malware.", False),
   r3=(3, "Hard to undo — assume the device and accounts are compromised until cleaned.", False),
   click="You open it. A credential-capture page loads or a file download starts (illustration only — nothing is opened).",
   nxt="Scammer (typical): \"Did you open it? It expires soon — please check now.\"", press="If you hesitate: \"The document will be deleted in 30 minutes.\""),
 "AI-Enabled Threat": dict(title="Voice / video impersonation (deepfake-style)",
   hook="A familiar voice or face makes the request feel authentic.",
   act="You are at the decision point. The message wants {ask}, in the name of someone you trust.",
   ext="You authorise a transfer or share private details believing it is the real person.",
   out="Funds leave to a new account and are moved on within minutes.",
   r2=(2, "Partly recoverable — call the real person on a number you already know; if money moved, contact your bank at once.", True),
   r3=(3, "Hard to undo — transfers to new accounts are quickly moved on. Report immediately.", True),
   click="You play or return the call. The 'person' repeats the request and insists it cannot wait (simulated).",
   nxt="Impersonator (typical): \"It cannot wait — I will explain later. Please do not tell anyone.\"", press="If you hesitate: \"I thought I could count on you.\""),
}
